### ISSUE TITLE
It will be nice to have a field called `public_key` in ETH `keyfile`

### ISSUE THREAD

**Issue by Aviksaikat** [fubuloubu/eth-keys#95]
It will be nice to have a field called `pubic_key` in ETH `keyfile`

## Example
```python
{
  "address": "e990ce1fd17a3e3bfa8ac37ddbfe766911a114ec",
  "crypto": {
    "cipher": "aes-128-ctr",
    "cipherparams": {
      "iv": "a3ffb3f314a8a38942dff99dae8890"
    },
    [...]
    },
  },
  "id": "2e9ba770-11ad-464b-bf3b-468cad97a1e8",
  "version": 3,
  "public_key" : "0x0000000dead0000000eth000hahha...." # extral field
}

**Comment by pacrob** [comment]
Sorry for the delay in response. The keyfile itself is handled by the library `eth-keyfile`, but it's a standard we conform to - https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

The version 4 keyfile does have the `pubkey` available, coming soon -> https://github.com/ethereum/eth-keyfile/pull/56
